on:
  push:
    tags:
      - "v*"

name: Release

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - os: ubuntu-latest
            r: "4.5.0"
          - os: macos-latest
            r: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Build package tarball
        if: matrix.config.os == 'macos-latest'
        run: R CMD build .

      - name: Upload to GitHub Release
        if: matrix.config.os == 'macos-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
